dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: CReZcbqveX4p0kP4b8oi9M0ekUtQGV3iBYgmRaY9A4GntzAoJN2VjeYHWvn4czWus4m+sZjbKOGgci+MB4EZmMLGWEdybjWii1WVTPk7zAeZ16EVIObXDUHIETge81aMmSjzNa6/N4D/tQ7hbw7NVI2GvBS0Iz8qGF6ktyFvKS+q6brYDLbRdQ2WPxy++o/By0NVKguNxO10HHzbIx+9EesGSEYfSEhNWMZhPrTQ9eYDQ6oFSf1Ms1lwjVn4iavi0jhU5HUYG8BbBS1vIgL81zWB1aLTN9ID5uzU8bo8VVhDuoq42QtikmQfvd+nraBMCzeNTE5GOz99p6/YL2GVSRL5KrDk9YpKwOdUS3t3GIYosIEaolObI0v6OZSeyq8oy2bxmhoOjYZZtHNr5mbnd/Z2PkYNwkb3IUGdqKsSlyYbnPOC+sEX/dLDaEVYNgxcKZHYviEl9dXBr3XPQszJz0wInYHVB+Li5VCqVucWCESmEBLwIpuCThn7Pks1t/XdMMPB3jZaAYDYbeURsxSjY6HOLEdT/Xw6qNzFPsW3b2Px2MHG7L22RU/9XHFLtZypmPRcYdm2ypUUD1H3OkcvtWeyAXN5kRbHKUYoh1+RAP0+PFQbjf2nnBfTdHpaShdCPTlw6Omt9f4wrdmkuq/qJzdfQSgsDj9AO8tLFLWQyIE=
